import React, { useContext, useEffect, useState } from 'react'
import * as yup from 'yup'
import { SyrupClient, AccountData } from '@maplelabs/syrup-sdk'
import {
  Governance,
  GovernanceAccountType,
  ProgramAccount,
  serializeInstructionToBase64,
} from '@solana/spl-governance'
import useWalletStore from 'stores/useWalletStore'
import { validateInstruction } from '@utils/instructionTools'
import {
  MapleFinanceLenderDepositForm,
  UiInstruction,
} from '@utils/uiTypes/proposalCreationTypes'
import Select from '@components/inputs/Select'
import { pools } from '@utils/instructions/MapleFinance/poolList'
import useGovernanceAssets from '@hooks/useGovernanceAssets'
import useWallet from '@hooks/useWallet'
import Input from '@components/inputs/Input'
import { uiToNative } from '@blockworks-foundation/mango-client'
import { tryGetMint } from '@utils/tokens'
import GovernedAccountSelect from '../../GovernedAccountSelect'
import { NewProposalContext } from '../../../new'
import { findATAAddrSync } from '@utils/ataTools'

const schema = yup.object().shape({
  governedAccount: yup.object().required('Governed token account is required'),
  poolName: yup.string().required('Pool Name is required'),
  depositAmount: yup
    .number()
    .moreThan(0, 'Deposit amount should be more than 0')
    .required('Deposit amount is required'),
})

const LenderDepositForm = ({
  index,
  governance,
}: {
  index: number
  governance: ProgramAccount<Governance> | null
}) => {
  const wallet = useWalletStore((s) => s.current)
  const connection = useWalletStore((s) => s.connection.current)
  const { anchorProvider } = useWallet()
  const { governedTokenAccountsWithoutNfts } = useGovernanceAssets()
  const { handleSetInstructions } = useContext(NewProposalContext)
  const [form, setForm] = useState<MapleFinanceLenderDepositForm>({})
  const [formErrors, setFormErrors] = useState({})

  const handleSetForm = ({ propertyName, value }) => {
    setFormErrors({})
    setForm({ ...form, [propertyName]: value })
  }

  const shouldBeGoverned = !!(index !== 0 && governance)

  // Only allow treasury v2 accounts, because Maple require authority to pay fees when withdrawing
  // Which is not possible for other governance's types
  const governancesV2 = governedTokenAccountsWithoutNfts.filter(
    (governance) =>
      governance.governance.account.accountType ===
        GovernanceAccountType.GovernanceV2 && governance.isSol
  )

  const getInstruction = async (): Promise<UiInstruction> => {
    const isValid = await validateInstruction({ schema, form, setFormErrors })
    const { governedAccount, poolName, depositAmount } = form

    if (
      !isValid ||
      !governedAccount ||
      !governedAccount.governance?.account ||
      !poolName ||
      !wallet ||
      !wallet.publicKey ||
      typeof depositAmount === 'undefined'
    ) {
      return {
        serializedInstruction: '',
        isValid: false,
        governance: governedAccount?.governance,
      }
    }

    const syrupClient = SyrupClient.load({
      // anchorProvider is enough match, that's why we force the compatibility with any
      provider: anchorProvider as any,
    })

    const pool = pools[poolName]

    const poolData = await syrupClient.program.account.pool.fetch(pool)

    const tokenMint = await tryGetMint(connection, poolData.baseMint)
    if (!tokenMint) {
      throw new Error(
        `Cannot load maple pool base mint for ${poolData.baseMint.toBase58()}`
      )
    }

    const lenderUser = governedAccount.pubkey

    // Use the baseMint ATA for deposit
    const tx = await syrupClient.lenderActions().deposit({
      amount: uiToNative(form.depositAmount!, tokenMint.account.decimals),
      pool: {
        address: pool,
        data: poolData as AccountData<'pool'>,
      },
      lenderUser,
      lenderLocker: findATAAddrSync(lenderUser, poolData.baseMint)[0],
    })

    if (!tx.instructions.length) {
      throw new Error(
        'Unexpected amount of instructions generated by deposit function (maple sdk)'
      )
    }

    const [instruction] = tx.instructions

    return {
      serializedInstruction: serializeInstructionToBase64(instruction),
      isValid: true,
      governance: governedAccount.governance,
      additionalSerializedInstructions: [],
    }
  }

  useEffect(() => {
    handleSetInstructions(
      {
        governedAccount: form.governedAccount?.governance,
        getInstruction,
      },
      index
    )
    // Only set instruction when form changes
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [form])

  return (
    <>
      <GovernedAccountSelect
        label="Governed Account"
        governedAccounts={governancesV2}
        onChange={(value) => {
          handleSetForm({ value, propertyName: 'governedAccount' })
        }}
        value={form.governedAccount}
        error={formErrors['governedAccount']}
        shouldBeGoverned={shouldBeGoverned}
        governance={governance}
      />

      <Select
        label="Pool"
        value={form.poolName}
        placeholder="Please select..."
        onChange={(value) => {
          handleSetForm({
            value,
            propertyName: 'poolName',
          })
        }}
        error={formErrors['poolName']}
      >
        {Object.keys(pools).map((name) => (
          <Select.Option key={name} value={name}>
            {name}
          </Select.Option>
        ))}
      </Select>

      <Input
        label="Deposit Amount"
        value={form.depositAmount}
        type="number"
        min="0"
        onChange={(evt) =>
          handleSetForm({
            value: evt.target.value,
            propertyName: 'depositAmount',
          })
        }
        error={formErrors['depositAmount']}
      />
    </>
  )
}

export default LenderDepositForm
