import React, { useContext, useEffect, useState } from 'react'
import * as yup from 'yup'
import { SyrupClient, AccountData } from '@maplelabs/syrup-sdk'
import {
  Governance,
  GovernanceAccountType,
  ProgramAccount,
  serializeInstructionToBase64,
} from '@solana/spl-governance'
import { PublicKey } from '@solana/web3.js'
import useWalletStore from 'stores/useWalletStore'
import { validateInstruction } from '@utils/instructionTools'
import {
  MapleFinanceWithdrawalRequestCloseForm,
  UiInstruction,
} from '@utils/uiTypes/proposalCreationTypes'
import Select from '@components/inputs/Select'
import { pools } from '@utils/instructions/MapleFinance/poolList'
import useGovernanceAssets from '@hooks/useGovernanceAssets'
import useWallet from '@hooks/useWallet'
import GovernedAccountSelect from '../../GovernedAccountSelect'
import { NewProposalContext } from '../../../new'
import { tryGetMint } from '@utils/tokens'
import Input from '@components/inputs/Input'
import { findATAAddrSync } from '@utils/ataTools'

const schema = yup.object().shape({
  governedAccount: yup.object().required('Governed token account is required'),
  poolName: yup.string().required('Pool Name is required'),
  withdrawalRequestAddress: yup
    .string()
    .required('Withdrawal Request Address is required'),
})

const WithdrawalRequestCloseForm = ({
  index,
  governance,
}: {
  index: number
  governance: ProgramAccount<Governance> | null
}) => {
  const wallet = useWalletStore((s) => s.current)
  const connection = useWalletStore((s) => s.connection.current)
  const { anchorProvider } = useWallet()
  const { governedTokenAccountsWithoutNfts } = useGovernanceAssets()
  const { handleSetInstructions } = useContext(NewProposalContext)
  const [form, setForm] = useState<MapleFinanceWithdrawalRequestCloseForm>({})
  const [formErrors, setFormErrors] = useState({})

  const handleSetForm = ({ propertyName, value }) => {
    setFormErrors({})
    setForm({ ...form, [propertyName]: value })
  }

  const shouldBeGoverned = !!(index !== 0 && governance)

  // Only allow treasury v2 accounts, because Maple require authority to pay fees when withdrawing
  // Which is not possible for other governance's types
  const governancesV2 = governedTokenAccountsWithoutNfts.filter(
    (governance) =>
      governance.governance.account.accountType ===
        GovernanceAccountType.GovernanceV2 && governance.isSol
  )

  const getInstruction = async (): Promise<UiInstruction> => {
    const isValid = await validateInstruction({ schema, form, setFormErrors })
    const { governedAccount, poolName, withdrawalRequestAddress } = form

    if (
      !isValid ||
      !governedAccount ||
      !governedAccount.governance?.account ||
      !poolName ||
      !wallet ||
      !wallet.publicKey ||
      !withdrawalRequestAddress
    ) {
      return {
        serializedInstruction: '',
        isValid: false,
        governance: governedAccount?.governance,
      }
    }

    const withdrawalRequestPubkey = new PublicKey(withdrawalRequestAddress)

    const syrupClient = SyrupClient.load({
      // anchorProvider is enough match, that's why we force the compatibility with any
      provider: anchorProvider as any,
    })

    const pool = pools[poolName]

    const poolData = await syrupClient.program.account.pool.fetch(pool)

    const withdrawalRequestData = await syrupClient.program.account.withdrawalRequest.fetch(
      withdrawalRequestPubkey
    )

    const sharesMint = await tryGetMint(connection, poolData.sharesMint)
    if (!sharesMint) {
      throw new Error(
        `Cannot load maple pool shares mint info for ${poolData.baseMint.toBase58()}`
      )
    }

    const lenderUser = governedAccount.pubkey

    // Use BaseMint ATA for fund reception
    const tx = await syrupClient.lenderActions().executeWithdrawalRequest({
      pool: {
        address: pool,
        data: poolData as AccountData<'pool'>,
      },

      withdrawalRequest: {
        address: withdrawalRequestPubkey,
        data: withdrawalRequestData,
      },

      lenderUser,
      lenderLocker: findATAAddrSync(lenderUser, poolData.baseMint)[0],
      lenderShareLocker: findATAAddrSync(lenderUser, poolData.sharesMint)[0],
    })

    if (tx.instructions.length !== 2) {
      throw new Error(
        'Unexpected amount of instructions generated by executeWithdrawalRequest function (maple sdk)'
      )
    }

    // Only get Withdrawal Request Close, ignore Withdrawal Request Execute
    // User need to create a separated instruction for that
    const [, instruction] = tx.instructions

    return {
      serializedInstruction: serializeInstructionToBase64(instruction),
      isValid: true,
      governance: governedAccount.governance,
      additionalSerializedInstructions: [],
    }
  }

  useEffect(() => {
    handleSetInstructions(
      {
        governedAccount: form.governedAccount?.governance,
        getInstruction,
      },
      index
    )
    // Only set instruction when form changes
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [form])

  return (
    <>
      <GovernedAccountSelect
        label="Governed Account"
        governedAccounts={governancesV2}
        onChange={(value) => {
          handleSetForm({ value, propertyName: 'governedAccount' })
        }}
        value={form.governedAccount}
        error={formErrors['governedAccount']}
        shouldBeGoverned={shouldBeGoverned}
        governance={governance}
      />

      <Select
        label="Pool"
        value={form.poolName}
        placeholder="Please select..."
        onChange={(value) => {
          handleSetForm({
            value,
            propertyName: 'poolName',
          })
        }}
        error={formErrors['poolName']}
      >
        {Object.keys(pools).map((name) => (
          <Select.Option key={name} value={name}>
            {name}
          </Select.Option>
        ))}
      </Select>

      <Input
        label="Withdrawal Request Address"
        value={form.withdrawalRequestAddress}
        type="string"
        onChange={(evt) =>
          handleSetForm({
            value: evt.target.value,
            propertyName: 'withdrawalRequestAddress',
          })
        }
        error={formErrors['withdrawalRequestAddress']}
      />
    </>
  )
}

export default WithdrawalRequestCloseForm
